#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Syntax Highlighting over-rides
ZSH_HIGHLIGHT_STYLES[globbing]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[command]='fg=white,bold,bg=green'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=white,bold,bg=green'
ZSH_HIGHLIGHT_STYLES[alias]='fg=white,bold,bg=green'
ZSH_HIGHLIGHT_STYLES[path]='bold'
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')

## To have paths colored instead of underlined
#ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'

## Reset colours if on a poor projector 
#ZSH_HIGHLIGHT_STYLES[command]='fg=white,bold,bg=green'
#ZSH_HIGHLIGHT_STYLES[builtin]='none'
#ZSH_HIGHLIGHT_STYLES[alias]='none'


# Configuration for Nodejs
export NODEJS_HOME=/home/jr0cket/apps/nodejs/bin
export PATH=$PATH:$NODEJS_HOME

# Configuration for MongoDB
export MONGODB_HOME=/home/jr0cket/apps/mongodb/current
export PATH=$PATH:$MONGODB_HOME/bin


# Add Play Framework to the execution PATH
export PLAY_HOME="/home/jr0cket/apps/play-framework/current"
export PATH=$PATH:$PLAY_HOME


## Aliases

# Dont make the terminal wait for you to kill the buffer in emacs
alias emacsclient='emacsclient --no-wait'
